package com.example.duizhan.model;

import android.content.Context;

import com.example.duizhan.R;
import com.example.duizhan.game.text.GameTextKey;
import com.example.duizhan.game.text.GameTextProvider;

public class AndroidGameTextProvider implements GameTextProvider {
    private final Context context;

    public AndroidGameTextProvider(Context context) {
        this.context = context.getApplicationContext();
    }

    @Override
    public String get(GameTextKey key, Object... args) {
        return context.getString(resId(key), args);
    }

    private int resId(GameTextKey key) {
        switch (key) {
            case BATTLE_START:
                return R.string.game_battle_start;
            case PAUSED:
                return R.string.game_paused;
            case RESUMED:
                return R.string.game_resumed;
            case HERO_DEAD_CANNOT_BUY:
                return R.string.game_hero_dead_cannot_buy;
            case HERO_MUST_RETURN_TO_FOUNTAIN:
                return R.string.game_hero_must_return_to_fountain;
            case GOLD_NOT_ENOUGH:
                return R.string.game_gold_not_enough;
            case BLUE_BUY_ITEM:
                return R.string.game_blue_buy_item;
            case BUY_SUCCESS:
                return R.string.game_buy_success;
            case BUILD_ALREADY_OPTIMAL:
                return R.string.game_build_already_optimal;
            case BUILD_APPLY_SUCCESS:
                return R.string.game_build_apply_success;
            case RECALL_SUCCESS:
                return R.string.game_recall_success;
            case RECALL_START:
                return R.string.game_recall_start;
            case RECALL_INTERRUPTED:
                return R.string.game_recall_interrupted;
            case RECALL_CANCEL_MOVE:
                return R.string.game_recall_cancel_move;
            case RECALL_CANCEL_ACTION:
                return R.string.game_recall_cancel_action;
            case RECALL_ALREADY_HOME:
                return R.string.game_recall_already_home;
            case ENTITY_RESPAWN:
                return R.string.game_entity_respawn;
            case MONSTER_SWEEP:
                return R.string.game_monster_sweep;
            case PROJECTILE_TOWER_FIRE:
                return R.string.game_projectile_tower_fire;
            case PROJECTILE_NORMAL_ATTACK:
                return R.string.game_projectile_normal_attack;
            case PROJECTILE_MAGIC_ATTACK:
                return R.string.game_projectile_magic_attack;
            case PROJECTILE_ARROW_ATTACK:
                return R.string.game_projectile_arrow_attack;
            case PROJECTILE_GOD_LIST:
                return R.string.game_projectile_god_list;
            case PROJECTILE_TALISMAN:
                return R.string.game_projectile_talisman;
            case PROJECTILE_STAR:
                return R.string.game_projectile_star;
            case ATTACK:
                return R.string.game_attack;
            case SKILL_DASH_SWEEP:
                return R.string.game_skill_dash_sweep;
            case SKILL_EYE_BEAM:
                return R.string.game_skill_eye_beam;
            case SKILL_FIRE_WHEEL:
                return R.string.game_skill_fire_wheel;
            case SKILL_THUNDER_CHAIN:
                return R.string.game_skill_thunder_chain;
            case SKILL_GIANT_STOMP:
                return R.string.game_skill_giant_stomp;
            case SKILL_MOON_FROST:
                return R.string.game_skill_moon_frost;
            case SKILL_EARTH_SPLIT:
                return R.string.game_skill_earth_split;
            case SKILL_BONE_TRAP:
                return R.string.game_skill_bone_trap;
            case SKILL_GOD_LIST:
                return R.string.game_skill_god_list;
            case SKILL_FIRE_CAGE:
                return R.string.game_skill_fire_cage;
            case SKILL_PAGODA_SEAL:
                return R.string.game_skill_pagoda_seal;
            case SKILL_HEALING_RAIN:
                return R.string.game_skill_healing_rain;
            case SKILL_SECONDARY:
                return R.string.game_skill_secondary;
            case SKILL_ULTIMATE:
                return R.string.game_skill_ultimate;
            case SKILL_NO_TARGET:
                return R.string.game_skill_no_target;
            case CONTROL_STUN:
                return R.string.game_control_stun;
            case CONTROL_SLOW:
                return R.string.game_control_slow;
            case CONTROL_SHIELD:
                return R.string.game_control_shield;
            case CONTROL_BLOCK:
                return R.string.game_control_block;
            case CONTROL_EMPOWER:
                return R.string.game_control_empower;
            case CONTROL_STEALTH:
                return R.string.game_control_stealth;
            case CONTROL_WALL_LEAP:
                return R.string.game_control_wall_leap;
            case SKILL_MIMIC:
                return R.string.game_skill_mimic;
            case SKILL_STEALTH:
                return R.string.game_skill_stealth;
            case SKILL_TALENT:
                return R.string.game_skill_talent;
            case TALENT_BURST:
                return R.string.game_talent_burst;
            case MIMIC_ACTIVE:
                return R.string.game_mimic_active;
            case TERRAIN_BRUSH_ENTER:
                return R.string.game_terrain_brush_enter;
            case TERRAIN_BRUSH_HINT:
                return R.string.game_terrain_brush_hint;
            case DAMAGE_TYPE_PHYSICAL:
                return R.string.game_damage_type_physical;
            case DAMAGE_TYPE_MAGIC:
                return R.string.game_damage_type_magic;
            case DAMAGE_TYPE_TRUE:
                return R.string.game_damage_type_true;
            case HEALING_RAIN_TEXT:
                return R.string.game_healing_rain_text;
            case BRUTE_SMASH:
                return R.string.game_brute_smash;
            case TALISMAN_MISSILE:
                return R.string.game_talisman_missile;
            case KILL_REWARD:
                return R.string.game_kill_reward;
            case KILL_SINGLE:
                return R.string.game_kill_single;
            case KILL_DOUBLE:
                return R.string.game_kill_double;
            case KILL_TRIPLE:
                return R.string.game_kill_triple;
            case KILL_QUADRA:
                return R.string.game_kill_quadra;
            case KILL_PENTA:
                return R.string.game_kill_penta;
            case KILL_GODLIKE:
                return R.string.game_kill_godlike;
            case KILL_LEGENDARY:
                return R.string.game_kill_legendary;
            case LEVEL_UP:
                return R.string.game_level_up;
            case BRUTE_WAVE:
                return R.string.game_brute_wave;
            case MINION_WAVE:
                return R.string.game_minion_wave;
            case MONSTER_BLACK_WIND:
                return R.string.game_monster_black_wind;
            case MONSTER_SAND:
                return R.string.game_monster_sand;
            case MONSTER_DRAGON_TURTLE:
                return R.string.game_monster_dragon_turtle;
            case MONSTER_KUNLUN:
                return R.string.game_monster_kunlun;
            case MONSTER_FLAME:
                return R.string.game_monster_flame;
            case MONSTER_PEACH:
                return R.string.game_monster_peach;
            case MONSTER_NINE_TAIL:
                return R.string.game_monster_nine_tail;
            case MONSTER_ROC:
                return R.string.game_monster_roc;
            case MONSTER_UNDERWORLD:
                return R.string.game_monster_underworld;
            case MONSTER_TAISHAN:
                return R.string.game_monster_taishan;
            case MONSTER_DRAGON_PALACE:
                return R.string.game_monster_dragon_palace;
            case MONSTER_PANGU:
                return R.string.game_monster_pangu;
            case MONSTER_GUARD:
                return R.string.game_monster_guard_format;
            case MONSTER_REFRESH:
                return R.string.game_monster_refresh;
            case RED_BUFF_GAIN:
                return R.string.game_red_buff_gain;
            case BLUE_BUFF_GAIN:
                return R.string.game_blue_buff_gain;
            case SPEED_BUFF_GAIN:
                return R.string.game_speed_buff_gain;
            case SHIELD_BUFF_GAIN:
                return R.string.game_shield_buff_gain;
            case SKILL_WIND_BLADE:
                return R.string.game_skill_wind_blade;
            case SKILL_YIN_YANG_ORB:
                return R.string.game_skill_yin_yang_orb;
            case SKILL_PHOENIX_FLAME:
                return R.string.game_skill_phoenix_flame;
            case SKILL_SPIRIT_CHAIN:
                return R.string.game_skill_spirit_chain;
            case SKILL_STARFALL:
                return R.string.game_skill_starfall;
            case SKILL_NETHER_WAVE:
                return R.string.game_skill_nether_wave;
            case SKILL_LOTUS_BARRIER:
                return R.string.game_skill_lotus_barrier;
            case RED_BUY_ITEM:
                return R.string.game_red_buy_item;
            case TEAM_WIN:
                return R.string.game_team_win;
            case NEUTRAL_KILLER:
                return R.string.game_neutral_killer;
            case SIDE_BLUE:
                return R.string.game_side_blue;
            case SIDE_RED:
                return R.string.game_side_red;
            case SIDE_NEUTRAL:
                return R.string.game_side_neutral;
            case HERO_ENTITY_NAME:
                return R.string.game_hero_entity_name_format;
            case TOWER_BLUE_OUTER:
                return R.string.game_tower_blue_outer;
            case TOWER_BLUE_MIDDLE:
                return R.string.game_tower_blue_middle;
            case TOWER_BLUE_HIGHLAND:
                return R.string.game_tower_blue_highland;
            case TOWER_RED_OUTER:
                return R.string.game_tower_red_outer;
            case TOWER_RED_MIDDLE:
                return R.string.game_tower_red_middle;
            case TOWER_RED_HIGHLAND:
                return R.string.game_tower_red_highland;
            case MINION_PREFIX_BLUE:
                return R.string.game_minion_prefix_blue;
            case MINION_PREFIX_RED:
                return R.string.game_minion_prefix_red;
            case MINION_PREFIX_NEUTRAL:
                return R.string.game_minion_prefix_neutral;
            case MINION_MELEE:
                return R.string.game_minion_melee;
            case MINION_RANGED:
                return R.string.game_minion_ranged;
            case MINION_BRUTE:
                return R.string.game_minion_brute;
            case MINION_ENTITY_NAME:
                return R.string.game_minion_entity_name_format;
            case FLOATING_DAMAGE:
                return R.string.game_floating_damage_format;
            case FLOATING_HERO_DAMAGE:
                return R.string.game_floating_hero_damage_format;
            case FLOATING_TYPED_DAMAGE:
                return R.string.game_floating_typed_damage_format;
            case FLOATING_BLOCK:
                return R.string.game_floating_block_format;
            case FLOATING_SHIELD:
                return R.string.game_floating_shield_format;
            case FLOATING_HEAL:
                return R.string.game_floating_heal_format;
            case FLOATING_LEVEL:
                return R.string.game_floating_level_format;
            case ITEM_EQUIPPED:
                return R.string.game_item_equipped_format;
            case ITEM_SLOT_WEAPON:
                return R.string.game_slot_weapon;
            case ITEM_SLOT_ARMOR:
                return R.string.game_slot_armor;
            case ITEM_SLOT_BOOTS:
                return R.string.game_slot_boots;
            case ITEM_SLOT_HAT:
                return R.string.game_slot_hat;
            case ITEM_SLOT_RELIC:
                return R.string.game_slot_relic;
            case ITEM_SLOT_CONSUMABLE:
                return R.string.game_slot_consumable;
            default:
                return R.string.game_battle_start;
        }
    }
}
